pipeline{
    agent any
    stages{
        stage(' for demo'){
            steps{
                echo "hello john"
        
            }
        }
        stage('more test'){
            steps{
                echo "singing"
            }
        }
    }
}